version: '3.9'

services:
  zabbix-db:
    image: mysql:8.0-oracle
    container_name: zabbix-db
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Africa/Cairo  
    command: [
      "--character-set-server=utf8",
      "--collation-server=utf8_bin",
      "--default-authentication-plugin=mysql_native_password"
    ]
    volumes:
      - zabbix-db-data:/var/lib/mysql
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.10
    restart: unless-stopped

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-7.0-latest
    container_name: zabbix-java-gateway
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.11
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      ZBX_JAVAGATEWAY: zabbix-java-gateway
      TZ: Africa/Cairo  
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.12
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Africa/Cairo  
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.13
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    init: true
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    networks:
      zabbix-network:
        ipv4_address: 172.20.240.14
    restart: unless-stopped

volumes:
  zabbix-db-data:
  zabbix-server-data:

networks:
  zabbix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.240.0/20
